services:
  mcp-tangle-blueprint:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-tangle-network/mcp-tangle-blueprint:latest}
    container_name: ${DOCKER_CONTAINER:-mcp-tangle-blueprint}
    platform: linux/amd64
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
